// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Supermarket1.API.Test
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AppointmentServiceFeature : object, Xunit.IClassFixture<AppointmentServiceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AppointmentServiceT.feature"
#line hidden
        
        public AppointmentServiceFeature(AppointmentServiceFeature.FixtureData fixtureData, Supermarket1_API_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "AppointmentService", "As a Developer\r\nI want to add a new Appointment throught API\r\nSo that Patients ca" +
                    "n book them", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("the endpoint https://localhost:5001/api/v1/appointment is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Dni",
                        "Name",
                        "Lastname",
                        "Age",
                        "Address"});
            table1.AddRow(new string[] {
                        "1",
                        "72837483",
                        "Simba",
                        "Tino",
                        "23",
                        "Lima"});
#line 8
        testRunner.And("A Patient is already stored", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Dni",
                        "Name",
                        "Lastname",
                        "SpecialtyId",
                        "Clinic"});
            table2.AddRow(new string[] {
                        "2",
                        "72837483",
                        "Simba",
                        "Tino",
                        "null",
                        "null"});
#line 11
        testRunner.And("A Doctor is already stored", ((string)(null)), table2, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add appointment")]
        [Xunit.TraitAttribute("FeatureTitle", "AppointmentService")]
        [Xunit.TraitAttribute("Description", "Add appointment")]
        [Xunit.TraitAttribute("Category", "appointment-adding")]
        public virtual void AddAppointment()
        {
            string[] tagsOfScenario = new string[] {
                    "appointment-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add appointment", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 16
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "StartAt",
                            "AppointmentDetailsId",
                            "PatientId",
                            "DoctorId"});
                table3.AddRow(new string[] {
                            "null",
                            "null",
                            "1",
                            "2"});
#line 17
        testRunner.When("an appointment Post request is sent", ((string)(null)), table3, "When ");
#line hidden
#line 20
        testRunner.Then("A response with Status 200 is received for appointment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "StartAt",
                            "AppointmentDetailsId",
                            "PatientId",
                            "DoctorId"});
                table4.AddRow(new string[] {
                            "null",
                            "null",
                            "1",
                            "2"});
#line 21
        testRunner.And("An appointment Resource is included in Response Body", ((string)(null)), table4, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add Appointment with Invalid Doctor")]
        [Xunit.TraitAttribute("FeatureTitle", "AppointmentService")]
        [Xunit.TraitAttribute("Description", "Add Appointment with Invalid Doctor")]
        [Xunit.TraitAttribute("Category", "appointment-invalid-doctor")]
        public virtual void AddAppointmentWithInvalidDoctor()
        {
            string[] tagsOfScenario = new string[] {
                    "appointment-invalid-doctor"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Appointment with Invalid Doctor", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "StartAt",
                            "AppointmentDetailsId",
                            "PatientId",
                            "DoctorId"});
                table5.AddRow(new string[] {
                            "null",
                            "null",
                            "1",
                            "202"});
#line 26
        testRunner.When("an appointment Post request is sent", ((string)(null)), table5, "When ");
#line hidden
#line 29
        testRunner.Then("A response with Status 400 is received for appointment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
        testRunner.And("a Message of \"Invalid Doctor.\" is included in Response Body for appointment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AppointmentServiceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AppointmentServiceFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
