// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Supermarket1.API.Test
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MedicalHistoryServiceTFeature : object, Xunit.IClassFixture<MedicalHistoryServiceTFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MedicalHistoryServiceT.feature"
#line hidden
        
        public MedicalHistoryServiceTFeature(MedicalHistoryServiceTFeature.FixtureData fixtureData, Supermarket1_API_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "MedicalHistoryServiceT", "As a Developer\r\nI want to add a new Medical History throught API\r\nSo that Doctors" +
                    " and Patients can watch the Patient Medical Record", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line hidden
#line 7
  testRunner.Given("the endpoint https://localhost:5001/api/v1/medicalhistory is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Dni",
                        "Name",
                        "Lastname",
                        "Age",
                        "Address"});
            table24.AddRow(new string[] {
                        "1",
                        "72837483",
                        "Simba",
                        "Tino",
                        "23",
                        "Lima"});
#line 8
  testRunner.And("A Patient is already stored", ((string)(null)), table24, "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Dni",
                        "Name",
                        "Lastname",
                        "Age",
                        "ClinicLocationId"});
            table25.AddRow(new string[] {
                        "2",
                        "88888888",
                        "Ricardo",
                        "Palma",
                        "23",
                        "null"});
#line 11
  testRunner.And("A Clinic is already stored", ((string)(null)), table25, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add Medical History")]
        [Xunit.TraitAttribute("FeatureTitle", "MedicalHistoryServiceT")]
        [Xunit.TraitAttribute("Description", "Add Medical History")]
        [Xunit.TraitAttribute("Category", "medical-history-adding")]
        public virtual void AddMedicalHistory()
        {
            string[] tagsOfScenario = new string[] {
                    "medical-history-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Medical History", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 16
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "PatientId",
                            "DoctorId"});
                table26.AddRow(new string[] {
                            "3",
                            "1",
                            "2"});
#line 17
  testRunner.When("a Medical History Post request is sent", ((string)(null)), table26, "When ");
#line hidden
#line 20
  testRunner.Then("A response with Status 200 is received for medical history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "PatientId",
                            "DoctorId"});
                table27.AddRow(new string[] {
                            "3",
                            "1",
                            "2"});
#line 21
  testRunner.And("A Medical History Resource is included in Response Body", ((string)(null)), table27, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add Medical History with Invalid Clinic")]
        [Xunit.TraitAttribute("FeatureTitle", "MedicalHistoryServiceT")]
        [Xunit.TraitAttribute("Description", "Add Medical History with Invalid Clinic")]
        [Xunit.TraitAttribute("Category", "medical-history-invalid-clinic")]
        public virtual void AddMedicalHistoryWithInvalidClinic()
        {
            string[] tagsOfScenario = new string[] {
                    "medical-history-invalid-clinic"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Medical History with Invalid Clinic", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 25
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "PatientId",
                            "DoctorId"});
                table28.AddRow(new string[] {
                            "3",
                            "1",
                            "404"});
#line 26
  testRunner.When("a Medical History Post request is sent", ((string)(null)), table28, "When ");
#line hidden
#line 29
  testRunner.Then("A response with Status 400 is received for medical history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
  testRunner.And("a Message of \"Invalid Clinic.\" is included in Response Body for medical history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add Medical History with Invalid patient")]
        [Xunit.TraitAttribute("FeatureTitle", "MedicalHistoryServiceT")]
        [Xunit.TraitAttribute("Description", "Add Medical History with Invalid patient")]
        [Xunit.TraitAttribute("Category", "medical-history-invalid-patient")]
        public virtual void AddMedicalHistoryWithInvalidPatient()
        {
            string[] tagsOfScenario = new string[] {
                    "medical-history-invalid-patient"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Medical History with Invalid patient", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 32
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "PatientId",
                            "DoctorId"});
                table29.AddRow(new string[] {
                            "3",
                            "404",
                            "1"});
#line 33
  testRunner.When("a Medical History Post request is sent", ((string)(null)), table29, "When ");
#line hidden
#line 36
  testRunner.Then("A response with Status 400 is received for medical history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
  testRunner.And("a Message of \"Invalid Patient.\" is included in Response Body for medical history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MedicalHistoryServiceTFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MedicalHistoryServiceTFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
